apiVersion: litmuchaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  name: kubernetes
  annotations:
    categories: "Kubernetes"
    vendor: "CNCF"
    createdAt: 2019-08-12T10:28:08Z
    repository: https://github.com/litmuschaos/community-charts
    support: https://slack.kubernetes.io/
    description: Injects generic kubernetes chaos
spec:
  displayName: Kubernetes
  description: >
    **Kubernetes** is an open-source system for automating deployment, scaling, and management of containerized
    applications. It groups containers that make up an application into logical units for easy management and discovery.
    Kubernetes builds upon 15 years of experience of running production workloads at Google, combined with best-of-breed
    ideas and practices from the community.

    * **StateChaos** - Injects random pod-level and container level-failures against specified app replicas

    * **NetworkChaos** - Injects random network jitters, delays and packet loss on the app replica pods

    ## Getting Started

    * Learn more about these experiments [here](https://github.com/litmuschaos/litmus)

  keywords:
    - Kubernetes
    - ContainerOrchestrators
  version: {{ VERSION }}
  maturity: alpha
  maintainers:
    - name: ksatchit
      email: karthik.s@mayadata.io
  minKubeVersion: 1.12.0
  provider:
    name: Mayadata
  links:
    - name: Kubernetes Website
      url: https://kubernetes.io
    - name: Source Code
      url: https://github.com/kubernetes/kubernetes
  icon:
    - link: https://proxy.duckduckgo.com/iu/?u=https%3A%2F%2Fpng.pngtree.com%2Fsvg%2F20170803%2Fkubernetes_ui_614933.png&f=1
      mediatype: image/png
